import { createMetaTitle } from "@/utils";
import SetPageTitle from "@/components/SetPageTitle";
import EventCondition from "@/components/EventCondition";
import Tag from "@/components/Tag";
import SectionTitle from "@/components/SectionTitle";
import { Skill } from "@/components/SkillPropertyList";
import SkillPropertyList from "@/components/SkillPropertyList";
import { skillLinks } from "@/constants";

// 💡 念のため、このページは完全に静的（SSG）であることを明示します
export const dynamic = "force-static";

const pageKey = "magic";
const title = skillLinks[pageKey].title;
const canonical = skillLinks[pageKey].path;
const description = skillLinks[pageKey].seoDesc;
export const metadata = {
  title,
  description,
  alternates: {
    canonical,
  },
};

export default async function HomePage() {
  const skills = [
    {
      name: "アクアエッジ",
      description:
        "キールが初期習得している晶霊術。楕円形の水の塊を相手にぶつける。",
      tp: 4,
      hit: 1,
      element: ["water"],
      type: "攻撃",
    },
    {
      name: "スプレッド",
      description: "出現した水の柱に当たった敵を浮かせながらダメージを与える。",
      requirement: "ウンディーネLv1",
      tp: 9,
      hit: 3,
      element: ["water"],
      type: "攻撃",
    },
    {
      name: "ヒール",
      description: "味方一人のHPを50%回復させる。",
      requirement: "ウンディーネLv1",
      requirement2: "シルフLv1",
      tp: 16,
      element: [],
      type: "回復",
    },
    {
      name: "アシッドレイン",
      description: "雨が当たった敵に対して与えるダメージが一時的に上昇する。",
      requirement: "ウンディーネLv10",
      requirement2: "ノームLv5",
      tp: 10,
      element: ["water"],
      type: "補助",
    },
    {
      name: "ナース",
      description: "味方全員のHPを40%回復させる。",
      requirement: "ウンディーネLv10",
      requirement2: "セルシウスLv1",
      tp: 42,
      element: ["water"],
      type: "回復",
    },
    {
      name: "キュア",
      description: "味方一人のHPを90%回復させる。",
      requirement: "ウンディーネLv15",
      requirement2: "マクスウェルLv1",
      tp: 32,
      element: ["water"],
      type: "回復",
    },
    {
      name: "リザレクション",
      description:
        "戦闘中は魔法陣の中にいる仲間のHPを最大90%ほど回復。メニュー画面では全員に適用される。",
      requirement: "ウンディーネLv20",
      requirement2: "レムLv1",
      tp: 60,
      element: ["water"],
      type: "回復",
    },
    {
      name: "レイズデッド",
      description: "戦闘不能の味方を回復し、HPも70%回復させる。",
      requirement: "ウンディーネLv20",
      requirement2: "ゼクンドゥスLv1",
      tp: 90,
      element: ["water"],
      type: "回復",
    },
    {
      name: "ウインドカッター",
      description: "キールが初期習得している晶霊術。風の刃を左右に敵に当てる。",
      requirement: "キール加入時に習得済み",
      tp: 7,
      element: ["wind"],
      type: "攻撃",
      hit: 2,
    },
    {
      name: "エアスラスト",
      description:
        "複数の風の刃を敵にぶつけて攻撃する。攻撃範囲にクセがあるが、うまく使えば中盤の敵の詠唱の妨げにも使える。",
      requirement: "シルフLv1",
      tp: 12,
      element: ["wind"],
      type: "攻撃",
      hit: 8,
    },
    {
      name: "コンセントレート",
      description:
        "サポート系晶霊術。戦闘中にのみ発動できて、仲間一人の集中力をアップさせる。",
      requirement: "シルフLv6",
      requirement2: "イフリートLv5",
      tp: 6,
      element: ["wind"],
      type: "補助",
    },
    {
      name: "サイクロン",
      description:
        "大きな竜巻を5、6秒ほど発生させて触れた敵にダメージを与える。",
      requirement: "シルフLv20",
      requirement2: "シャドウLv9",
      tp: 44,
      element: ["wind"],
      type: "攻撃",
      hit: 16,
    },
    {
      name: "ファイアボール",
      description:
        "キールが初期習得している晶霊術。小さな火玉を3つ順々と敵に当てて攻撃する。",
      requirement: "キール加入時に習得済み",
      tp: 7,
      element: ["fire"],
      type: "攻撃",
      hit: 3,
    },
    {
      name: "イラプション",
      description:
        "マグマの噴火に当たった敵を3回攻撃し、その後に降ってくる岩石でも攻撃する。範囲はなかなか広いため、敵が固まっている場所に有効。",
      requirement: "イフリートLv1",
      tp: 18,
      element: ["fire"],
      type: "攻撃",
      hit: 7,
    },
    {
      name: "シャープネス",
      description:
        "サポート系晶霊術。戦闘中にのみ仲間一人の攻撃力を上昇させる。重ね掛けは無効となる。",
      requirement: "イフリートLv5",
      requirement2: "ウンディーネLv7",
      tp: 6,
      element: ["fire"],
      type: "補助",
      hit: 7,
    },
    {
      name: "シャープネス",
      description:
        "敵の前に炎の壁を作成して、触れた敵にダメージを与える。1回ダメージを与えたり、他の晶霊術の発動によって壁は消滅する。使い所が難しい。",
      requirement: "イフリートLv12",
      requirement2: "ノームLv9",
      tp: 12,
      element: ["fire"],
      type: "攻撃",
      hit: 1,
    },
    {
      name: "エクスプロード",
      description:
        "巨大な爆発を発生させて敵にダメージを与える。敵が浮き上がって叩きつけられるとダウン状態となる。後半ではかなりフリンジしやすい強力な術。",
      requirement: "イフリートLv15",
      requirement2: "ヴォルトLv9",
      tp: 36,
      element: ["fire"],
      type: "攻撃",
      hit: 4,
    },
    {
      name: "グレイブ",
      description: "-",
      requirement: "メルディ加入時に習得済み",
      tp: 7,
      element: ["earth"],
      type: "攻撃",
      hit: 3,
    },
    {
      name: "ロックブレイク",
      description: "-",
      requirement: "ノームLv1",
      tp: 18,
      element: ["earth"],
      type: "攻撃",
      hit: 6,
    },
    {
      name: "グランドダッシャー",
      description: "-",
      requirement: "ノームLv21",
      requirement2: "シャドウLv10",
      tp: 48,
      element: ["earth"],
      type: "攻撃",
      hit: 5,
    },
    {
      name: "アイスニードル",
      description: "-",
      requirement: "メルディ加入時に習得済み",
      tp: 6,
      element: ["ice"],
      type: "攻撃",
      hit: 3,
    },
    {
      name: "フリーズランサー",
      description: "-",
      requirement: "セルシウスLv1",
      tp: 21,
      element: ["ice"],
      type: "攻撃",
      hit: 4,
    },
    {
      name: "レジスト",
      description: "-",
      requirement: "セルシウスLv10",
      requirement2: "ノームLv7",
      tp: 6,
      element: ["ice"],
      type: "補助",
    },
    {
      name: "ブリザード",
      description: "-",
      requirement: "セルシウスLv12",
      requirement2: "シルフLv15",
      tp: 20,
      element: ["ice"],
      type: "攻撃",
      hit: 3,
    },
    {
      name: "アブソリュート",
      description: "-",
      requirement: "セルシウスLv14",
      requirement2: "ヴォルトLv12",
      tp: 30,
      element: ["ice"],
      type: "攻撃",
      hit: 3,
    },
    {
      name: "ライトニング",
      description: "-",
      requirement: "メルディ加入時に習得済み",
      tp: 7,
      element: ["thunder"],
      type: "攻撃",
      hit: 1,
    },
    {
      name: "サンダーブレード",
      description: "-",
      requirement: "ヴォルトLv1",
      tp: 24,
      element: ["thunder"],
      type: "攻撃",
      hit: 4,
    },
    {
      name: "チャージ",
      description: "-",
      requirement: "ヴォルトLv5",
      requirement2: "シルフLv13",
      tp: 100,
      element: ["thunder"],
      type: "補助",
    },
    {
      name: "リカバー",
      description: "-",
      requirement: "ヴォルトLv6",
      requirement2: "ノームLv11",
      tp: 10,
      element: ["thunder"],
      type: "回復",
    },
    {
      name: "インディグネイション",
      description: "-",
      requirement: "ヴォルトLv15",
      requirement2: "レムLv10",
      tp: 52,
      element: ["thunder"],
      type: "攻撃",
      hit: 2,
    },
    {
      name: "レイ",
      description: "-",
      requirement: "レムLv1",
      tp: 30,
      element: ["light"],
      type: "攻撃",
      hit: 7,
    },
    {
      name: "ホーリーブレス",
      description: "-",
      requirement: "レムLv15",
      requirement2: "イフリートLv20",
      tp: 8,
      element: ["light"],
      type: "補助",
    },
    {
      name: "ホーリーランス",
      description: "-",
      requirement: "レムLv21",
      requirement2: "マクスウェルLv20",
      tp: 52,
      element: ["light"],
      type: "攻撃",
      hit: 9,
    },
    {
      name: "ダークフォース",
      description: "-",
      requirement: "シャドウLv1",
      tp: 32,
      element: ["dark"],
      type: "攻撃",
      hit: 6,
    },
    {
      name: "バリアー",
      description: "-",
      requirement: "シャドウLv5",
      requirement2: "ヴォルトLv10",
      tp: 6,
      element: ["dark"],
      type: "補助",
    },
    {
      name: "ディープミスト",
      description: "-",
      requirement: "シャドウLv5",
      requirement2: "ウンディーネLv15",
      tp: 6,
      element: ["dark"],
      type: "補助",
    },
    {
      name: "ブラッディハウリング",
      description: "-",
      requirement: "シャドウLv23",
      requirement2: "ゼクンドゥスLv18",
      tp: 72,
      element: ["dark"],
      type: "攻撃",
      hit: 4,
    },
    {
      name: "メテオスウォーム",
      description: "-",
      requirement: "マクスウェルLv1",
      tp: 60,
      element: ["origin"],
      type: "攻撃",
      hit: 7,
    },
    {
      name: "シューティングスター",
      description: "-",
      requirement: "マクスウェルLv26",
      requirement2: "ゼクンドゥスLv26",
      tp: 80,
      element: ["origin"],
      type: "攻撃",
      hit: 12,
    },
    {
      name: "ディストーション",
      description: "-",
      requirement: "ゼクンドゥスLv1",
      tp: 64,
      element: ["time"],
      type: "攻撃",
      hit: 12,
    },
    {
      name: "スクラグネイション",
      description: "-",
      requirement: "ゼクンドゥスLv5",
      requirement2: "セルシウスLv30",
      tp: 16,
      element: ["time"],
      type: "補助",
    },
    {
      name: "ディレイ",
      description: "-",
      requirement: "ゼクンドゥスLv20",
      requirement2: "ノームLv30",
      tp: 60,
      element: ["time"],
      type: "補助",
    },
    {
      name: "+メディカルプラス",
      description: "習得していると戦闘中の回復系晶霊術の効果がアップする。",
      requirement: "シルフLv10",
      requirement2: "レムLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+メンタルチャージ",
      description: "習得していると戦闘後のTP回復量がアップする。",
      requirement: "ノームLv5",
      requirement2: "シルフLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+メディカルプラス",
      description: "習得していると戦闘中の回復系晶霊術の効果がアップする。",
      requirement: "シルフLv10",
      requirement2: "レムLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+フリーズガード",
      description:
        "習得していると戦闘中にパーティ全体が凍結状態にならなくなる。",
      requirement: "セルシウスLv10",
      requirement2: "イフリートLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+パラライガード",
      description:
        "習得していると戦闘中にパーティ全体が麻痺状態にならなくなる。",
      requirement: "ヴォルトLv10",
      requirement2: "ウンディーネLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+ライフレスキュー",
      description:
        "習得していると戦闘中にHPが少なくなった場合に徐々に回復する効果が現れる。",
      requirement: "ノームLv10",
      requirement2: "レムLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+アイテムゲッター",
      description:
        "戦闘中にテクニカルスマッシュが発生するとアイテム入手にボーナス2ポイント。",
      requirement: "シルフLv10",
      requirement2: "マクスウェルLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+メンタルサプライ",
      description:
        "習得していると戦闘中に受けたダーメージに応じてTPが回復する。",
      requirement: "ノームLv20",
      requirement2: "マクスウェルLv20",
      element: [],
      type: "特殊",
    },
    {
      name: "+ヒールウェポン",
      description: "習得していると戦闘中に敵を倒すとHPが回復する。",
      requirement: "レムLv10",
      requirement2: "シャドウLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+ライフアップ",
      description: "習得している状態でレベルアップするとHP+2のボーナスが付く。",
      requirement: "マクスウェルLv10",
      requirement2: "セルシウスLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+メンタルアップ",
      description: "習得している状態でレベルアップするとTP+1のボーナスが付く。",
      requirement: "ゼクンドゥスLv10",
      requirement2: "イフリートLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+ポイズンガード",
      description: "習得していると戦闘中にパーティ全体が毒状態にならない。",
      requirement: "マクスウェルLv10",
      requirement2: "シャドウLv10",
      element: [],
      type: "特殊",
    },
    {
      name: "+ドレインガード",
      description:
        "習得していると戦闘中にパーティ全体が能力低下の状態にならない。",
      requirement: "ゼクンドゥスLv10",
      requirement2: "マクスウェルLv10",
      element: [],
      type: "特殊",
    },
  ] as Skill[];

  return (
    <article>
      <SetPageTitle title={title} />
      {/* <h2>おすすめの晶霊術</h2>
      <div className="advice">
        <p>準備中</p>
      </div> */}
      <SectionTitle type="skill">晶霊術一覧</SectionTitle>
      <SkillPropertyList skills={skills} />
    </article>
  );
}
